<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HRS35RE" failures="0" tests="4" name="tests.Loginqaontime" time="7.094" errors="1" timestamp="2020-01-07T19:38:48 EET" skipped="0">
  <testcase classname="tests.Loginqaontime" name="Should_BeAbleToCreateIssue_When_ProvidingCorrectData" time="4.059"/>
  <testcase classname="tests.Loginqaontime" name="abc" time="0.004"/>
  <testcase classname="tests.Loginqaontime" name="add_issue_Should_Not_Work_Then_Issue_Name_Missing" time="3.023"/>
  <testcase classname="tests.Loginqaontime" name="add_issue_Should_Not_work_SeverityToBig" time="0.008">
    <error message="Method tests.Loginqaontime.add_issue_Should_Not_work_SeverityToBig() didn&#039;t finish within the time-out 1" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tests.Loginqaontime.add_issue_Should_Not_work_SeverityToBig() didn't finish within the time-out 1
at java.base@13.0.1/sun.nio.ch.SocketDispatcher.write0(Native Method)
at java.base@13.0.1/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54)
at java.base@13.0.1/sun.nio.ch.NioSocketImpl.tryWrite(NioSocketImpl.java:399)
at java.base@13.0.1/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:414)
at java.base@13.0.1/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:441)
at java.base@13.0.1/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:825)
at java.base@13.0.1/java.net.Socket$SocketOutputStream.write(Socket.java:1007)
at app//org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
at app//org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
at app//org.apache.http.impl.io.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:146)
at app//org.apache.http.impl.io.ContentLengthOutputStream.flush(ContentLengthOutputStream.java:101)
at app//org.apache.http.entity.ByteArrayEntity.writeTo(ByteArrayEntity.java:117)
at app//org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
at app//org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
at app//org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
at app//org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
at app//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
at app//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at app//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at app//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at app//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
at app//org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
at app//org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
at app//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
at app//org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
at app//tests.Loginqaontime.add_issue_Should_Not_work_SeverityToBig(Loginqaontime.java:62)
at java.base@13.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@13.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@13.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@13.0.1/java.lang.reflect.Method.invoke(Method.java:567)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.base@13.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@13.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@13.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@13.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@13.0.1/java.lang.Thread.run(Thread.java:830)
]]>
    </error>
  </testcase> <!-- add_issue_Should_Not_work_SeverityToBig -->
</testsuite> <!-- tests.Loginqaontime -->
